# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/mobty-website-test/AlMobtyFrontend
          git pull
          npm install --force
          npm run build
          pm2 restart AlMobtyFrontend
